export const AUTH_ACTION_TYPES ={
    SET_CURRENT_USER: "auth/SET_CURRENT_USER",
    REMOVE_CURRENT_USER: "auth/REMOVE_CURRENT_USER",
    SET_CAREERPATH_SELECTED:"auth/SET_CAREERPATH_SELECTED",
    SET_CAREERPATH:"auth/SET_CAREERPATH"
}