name: check-codetivite-frontend
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: VictorDanilov/react-project-checker-action@v0.0.1-alpha3
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: yarn run build
